apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawclaw
  labels:
    app: pawsandclawpet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pawsandclawpet
  template:
    metadata:
      labels:
        app: pawsandclawpet
    spec:
      containers:
      - name: pawsandclaw
        image: us.icr.io/pawclaw/pawsandclawpet
        ports:
        - containerPort: 5000